FROM python:3.11-slim-buster as builder

COPY ./src/requirements.txt /tmp/requirements.txt
COPY ./src /usr/src/app

RUN pip install -r /tmp/requirements.txt

WORKDIR /usr/src/app/score-service

CMD ["python3", "db.py"]
